import Node from "./node";
import Linkedlist from "./linkedList";

let linkedList = new Linkedlist();
linkedList.print();
linkedList.push(3);
linkedList.push(5);
linkedList.push(7);
linkedList.insertAtFront(1);
//linkedList.insertAtFront("Hi");
linkedList.insertAtPosition(10, 1);
linkedList.print();
console.log("Reverse:");
linkedList.reverse();
linkedList.print();
console.log("Recursive Reverse:");
linkedList.recursiveReverse();
linkedList.print();
let element = linkedList.getKthLastElement(3);
console.log("Kth element: ", element);
linkedList.deleteElement(89);
linkedList.deleteElement(10);
linkedList.print();
console.log("Delete at position called: ");
linkedList.deleteAtPosition(3);
linkedList.print();
console.log("Delete called: ");
linkedList.delete();
linkedList.print();
